task:
  name: Linux x86_64 (Intel)
  container:
    image: rocker/r-ver:4.4
    cpu: 2
    memory: 4G

  env:
    RENV_CONFIG_ACTIVE: "FALSE"

  cpu_info_script: grep -m1 "model name" /proc/cpuinfo

  avx512_check_script: |
    grep -q avx512f /proc/cpuinfo \
      && echo "AVX-512 available — proceeding" \
      || (echo "AVX-512 not available on this runner — skipping"; exit 0)

  install_system_script: |
    apt-get update -qq
    apt-get install -y python3-venv python3-dev python3-pip

  install_r_packages_script: |
    Rscript -e "
      install.packages('remotes')
      remotes::install_github('keneo/play-zvec/rzvec')
      remotes::install_github('keneo/play-zvec/rszvec')
    "

  test_script: Rscript docker/ci-test.R
